routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/','FrontController@index')->name('home');

Route::get('posts/{name?}/{post_type}','FrontController@showPostType')->name('posts');

Route::get('post/{post_type}/{post}', 'FrontController@show')->name('post');

Route::get('contact','FrontController@contact')->name('front_contact');

Route::post('search','FrontController@search');

//Route::get('posts/{type}/{name?}','FrontController@showPostType')->name('type');

Route::post('email','FrontController@sendEmail');

Auth::routes();

Route::middleware(['auth', ])->group(function () {
    Route::resource('admin/post','PostController');
    Route::post('delete','PostController@multipleDeletion')->name('multipleDeletion');
    Route::post('delete/definitive','PostController@definitiveDeletion')->name('definitiveDeletion');
    Route::get('trash','PostController@trash')->name('trash');
    Route::get('restore/{id}','PostController@restore')->name('restore');
});










//Route::get('/admin', 'PostController@index')->name('home');

resources/views/partials/authentication.blade.php
@if (Auth::check())
    <a  href="{{route('post.index')}}">Tableau de bord</a> 
    <a  class="float-md-right"
        href="{{route('logout')}}"
        onclick="event.preventDefault();
                document.getElementById('logout-form').submit();">
        Se déconnecter
    </a> 
    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
    </form>            
    
@else
    <a class="float-right" href="{{ route('login') }}">Se connecter</a>
@endif

resources/views/partials/menu.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-transparent sticky-top">
    <a class="navbar-brand" href="{{route('home')}}">
        Accueil 
        <span class="sr-only">(current)</span>
    </a>  

    <button class="navbar-toggler" 
            type="button" 
            data-toggle="collapse" 
            data-target="#navbarSupportedContent" 
            aria-controls="navbarSupportedContent" 
            aria-expanded="false" 
            aria-label="Toggle navigation"
    >
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">        
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{{route('posts',['formation','continue'])}}">
                    Formations
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('posts',['stage','apprentissage'])}}">
                    Stages
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{action('FrontController@contact')}}">
                    Contact
                </a>
            </li>
        </ul>                 
    </div>
</nav>

resources/views/partials/search.blade.php
<form   method="POST" 
        action="{{action('FrontController@search')}}" 
        class="form-inline float-md-right my-2 my-lg-0">
    {{ csrf_field() }}
    @if($errors->has('word'))
        <p class="error my-auto text-danger mr-sm-2">
            {{$errors->first('word')}}
        </p> 
    @endif
    <input  name="word" 
            class="form-control mr-sm-2" 
            type="search" 
            placeholder="Rechercher" 
            aria-label="Rechercher"
    >
    <button class="btn btn-outline-success" type="submit">Rechercher</button>
</form>

resources/views/partials/showOneListItem.blade.php
<li class="list-group-item">
    <div class="row">
        @if(!is_null($post->picture))
        <div class="col-xs-6 col-md-3">
            <a href="#" class="thumbnail">
            <img width="171" 
                 src="{{url('storage', ['images', $post->picture->link])}}" 
                 alt="{{$post->picture->title}}">
            </a>
        </div>
        @endif
        <div class="col-xs-6 col-md-9">
            <h2>
                <a href="{{route('post', ['post_type' => $post->post_type ,'id' => $post->id])}}">
                    {{$post->title}}
                </a>
            </h2>
            {{$post->description}}
            <p>{{$post->post_type}}</p>
            <p>{{$post->id}}</p>
            <p>{{$post->status}}</p>
        </div>
    </div>
    <p>Date de début: {{$post->init_date}}</p>
</li>